# Generated by Django 3.1.13 on 2021-09-03 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20210824_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'created', 'ordering': ['created', 'modified']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'get_latest_by': 'created', 'ordering': ['created', 'modified']},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'get_latest_by': 'created', 'ordering': ['created', 'modified']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.photo'),
        ),
    ]
