# Generated by Django 3.1.13 on 2021-08-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Set to true when the user have verified its email address.', verbose_name='verified'),
        ),
    ]
